[package]
name = "tracing-setup"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
axum-tracing-opentelemetry = "0.38.0"
opentelemetry = { version = "0.32.0", features = ["metrics"] }
opentelemetry-otlp = { version = "0.32.0", features = [
    "metrics",
    "logs",
    "trace",
    "grpc-tonic",
], default-features = false }
opentelemetry-resource-detectors = "0.11.0"
opentelemetry-semantic-conventions = "0.32.1"
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio", "metrics"] }
serde_json = "1"
tonic-tracing-opentelemetry = "0.38.0"
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-opentelemetry = "0.33.0"
tracing-opentelemetry-instrumentation-sdk = { version = "0.38.1", features = [
    "tracing_level_info",
] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
